[package]
name = "awtrix-gui"
version = "0.1.0"
edition = "2024"
description = "A GUI for the awtrix clock."
authors = ["bircni"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/bircni/Awtrix-GUI"
keywords = ["awtrix", "gui", "clock", "display", "iot", "embedded"]
categories = ["gui", "hardware-interfaces", "network-programming", "iot"]

[package.metadata.bundle]
name = "AwtrixGUI"
identifier = "bircni.AwtrixGUI"
icon = [
    "./../res/mac-icons/icon_16x16.png",
    "./../res/mac-icons/icon_32x32.png",
    "./../res/mac-icons/icon_128x128.png",
    "./../res/mac-icons/icon_256x256.png",
    "./../res/mac-icons/icon_16x16@2x.png",
    "./../res/mac-icons/icon_32x32@2x.png",
    "./../res/mac-icons/icon_128x128@2x.png",
]
version = "0.1.0"
resources = ["./../res/mac-icons/icon*.png"]
copyright = "© 2025 bircni"
short_description = "A GUI for the awtrix clock."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[patch.crates-io]
# egui-notify = { git = "https://github.com/ItsEthra/egui-notify", branch = "master" }

[dependencies]
# Error handling
anyhow = "1"
# Parsing
serde = { version = "1", features = ["derive"] }
serde_json = "1"
# GUI
eframe = "0.33"
egui = "0.33"
egui-notify = "0.21"
egui_extras = { version = "0.33", features = ["syntect", "image"] }
image = "0.25"
open = "5.3"
parking_lot = "0.12"
ureq = "3.1.4"

[dev-dependencies]
egui_kittest = { version = "0.33", features = ["wgpu", "snapshot"] }
eframe = { version = "0.33", features = ["wgpu"] }
tokio = { version = "1", features = ["time", "rt", "macros"] }
wgpu = "27"


[lints.rust]
unsafe_code = "deny"
deprecated = "warn"
elided_lifetimes_in_paths = "warn"
rust_2021_prelude_collisions = "warn"
semicolon_in_expressions_from_macros = "warn"
trivial_numeric_casts = "warn"
unsafe_op_in_unsafe_fn = "warn"                         # `unsafe_op_in_unsafe_fn` may become the default in future Rust versions: https://github.com/rust-lang/rust/issues/71668
unused_extern_crates = "warn"
unused_import_braces = "warn"
unused_lifetimes = "warn"

[lints.rustdoc]
all = "warn"
missing_crate_level_docs = "warn"

[lints.clippy]
all = "warn"
correctness = "warn"
suspicious = "warn"
style = "warn"
complexity = "warn"
perf = "warn"
pedantic = "warn"
nursery = "warn"

# Additional lints from https://rust-lang.github.io/rust-clippy/master/index.html?groups=restriction
allow_attributes = "warn"
allow_attributes_without_reason = "warn"
assertions_on_result_states = "warn"
create_dir = "warn"
clone_on_ref_ptr = "warn"
expect_used = "warn"
missing_assert_message = "warn"
panic_in_result_fn = "warn"
str_to_string = "warn"
todo = "warn"
unwrap_used = "warn"
unimplemented = "warn"
wildcard_enum_match_arm = "warn"
